### ISSUE TITLE
Задание для новичка

### ISSUE THREAD

**Issue by Lyumih** [englishextra/englishextra.github.io#3]
Добрый день!
Понравился ваш проект.
Я хочу влиться в open-source.
У вас есть какое-нибудь задание для новичка?
Могу я расчитывать на менторство от вас при отправке пулл-реквеста.

**Comment by englishextra** [comment]
Привет. Возьмите скрипт управляющий интерфейсом найдите в нем огрехи и добавим вас в контрибьютеры. Выберите здесь https://github.com/englishextra/englishextra.github.io/tree/master/libs как вы поняли это либы на страницы сайта. В любой из этих либ выберите из src js файл и исходя из ваших знаний опыта найдите огрехи оптимизации и пошлите их пулл реквестом. Тогда будет от чего отталкиваться. Пишите далее по англ иначе другие разработчики подумают что это междусобойчик - а это ведь площадка для совместного коллаборирования. ничего не бойтесь. мои контакты вы найдете. и да - я сам любитель и не такой уж профи - большой стаж - это да.
